Repository DeveloperAcademy-POSTECH/2025-C3-M12-4T2D, pull requests merged in 2025-06, with the labels that each got.

#27 [hoxfix] ProjectView 파일 Project로 선언되었던 버그 수정
  C3-4T2D/View/ProjectView/ProjectList.swift
  C3-4T2D/View/ProjectView/ProjectView.swift
Labels: 🐞 bug

#31 [Feature] Router활용 Navigation시스템 구현
  C3-4T2D/App/Router.swift
  C3-4T2D/View/ContentView.swift
  C3-4T2D/View/Local/ProjectSectionCard.swift
  C3-4T2D/View/MainView/MainView.swift
Labels: enhancement, feature

#40 [Feature] lightMode 강제 고정을 위한 info.plist 수정
  C3-4T2D/Info.plist
Labels: enhancement, feature, 🤗 리뷰 기다리는중

#45 [Feature] App Icon Asset 추가
  C3-4T2D/Assets.xcassets/AppIcon.appiconset/Contents.json
  C3-4T2D/Assets.xcassets/AppIcon.appiconset/dark.png
  C3-4T2D/Assets.xcassets/AppIcon.appiconset/light.jpg
Labels: enhancement

#55 [Feature] Project View 내 Comment Modal 구현
  C3-4T2D/Extensions/DateExtensions.swift
  C3-4T2D/View/ProjectView/Component/CommentModal.swift
  C3-4T2D/View/ProjectView/Component/LikeCommentBar.swift
  C3-4T2D/View/ProjectView/ProjectView.swift
Labels: Components, feature, 📱 UI, 🤗 리뷰 기다리는중

#57 [Feature] MainView UI 작업 #54
  C3-4T2D/App/C3_4T2DApp.swift
  C3-4T2D/Assets.xcassets/button.imageset/Contents.json
  C3-4T2D/Assets.xcassets/button.imageset/button.png
  C3-4T2D/Assets.xcassets/fire.imageset/Contents.json
  C3-4T2D/Assets.xcassets/fire.imageset/🔥 불.png
  C3-4T2D/Assets.xcassets/head.imageset/Contents.json
  C3-4T2D/Assets.xcassets/head.imageset/Group 1707481983.png
  C3-4T2D/Assets.xcassets/note.imageset/Contents.json
  C3-4T2D/Assets.xcassets/note.imageset/📒 노트.png
  C3-4T2D/Assets.xcassets/pallet.imageset/Contents.json
  C3-4T2D/Assets.xcassets/pallet.imageset/🎨 팔레트.png
  C3-4T2D/Assets.xcassets/profile.imageset/Contents.json
  C3-4T2D/Assets.xcassets/profile.imageset/Group 1707481982.jpg
  C3-4T2D/View/Local/MainHeader.swift
  C3-4T2D/View/MainView/MainView.swift
Labels: feature, 📱 UI, 🤗 리뷰 기다리는중

#59 [Refactor] ViewExtension 생성 및 Shared 폴더 생성
  C3-4T2D/Extensions/ViewExtensions.swift
  C3-4T2D/Shared/DatePickerSheet.swift
  C3-4T2D/View/Create/CreateView.swift
Labels: feature, 🤗 리뷰 기다리는중

#66 [Feature] 진행중인 과정 뷰 생성 및 ProjectSectionCard 노출 로직 변경 #61
  C3-4T2D/View/Local/ActiveProjectCard.swift
  C3-4T2D/View/Local/GridImageCard.swift
  C3-4T2D/View/Local/PostListCard.swift
  C3-4T2D/View/Local/ProjectSectionCard.swift
  C3-4T2D/View/MainView/MainView.swift
Labels: Components, feature, 🤗 리뷰 기다리는중

#73 [Feature] onBoarding 개발 완료 작업
  C3-4T2D/Extensions/Colors.swift
  C3-4T2D/Extensions/DateExtensions.swift
  C3-4T2D/Extensions/OnboardingExtensions.swift
  C3-4T2D/Extensions/ViewExtensions.swift
  C3-4T2D/Shared/DatePickerSheet.swift
  C3-4T2D/View/Common/ActionButton.swift
  C3-4T2D/View/MainView/MainView.swift
  C3-4T2D/View/OnboardingView/Enum/TextFieldType.swift
  C3-4T2D/View/OnboardingView/Local/OnboardingBanner.swift
  C3-4T2D/View/OnboardingView/Local/OnboardingDateField.swift
  C3-4T2D/View/OnboardingView/Local/OnboardingFormState.swift
  C3-4T2D/View/OnboardingView/Local/OnboardingTextField.swift
  C3-4T2D/View/OnboardingView/OnboardingView.swift
Labels: enhancement, Components, feature

#76 [Feature] 촬영후 CreateView로의 이미지 전달 기능 구현
  C3-4T2D/View/Camera/CameraView.swift
  C3-4T2D/View/Create/CreateView.swift
  C3-4T2D/View/Create/Local/CreatePhoto.swift
  C3-4T2D/View/Create/Local/ProjectSelector.swift
  C3-4T2D/View/MainView/MainView.swift
Labels: enhancement, feature

#79 [Feature] CreateView project #78
  C3-4T2D/Model/Project/Post.swift
  C3-4T2D/Model/SwiftDataManager.swift
  C3-4T2D/View/Create/CreateView.swift
  C3-4T2D/View/Create/Local/CreateHeader.swift
  C3-4T2D/View/Create/Local/ProjectSelector.swift
  C3-4T2D/View/Local/ActiveProjectCard.swift
  C3-4T2D/View/Local/GridImageCard.swift
  C3-4T2D/View/Local/PostListCard.swift
  C3-4T2D/View/Local/ProjectSectionCard.swift
  C3-4T2D/View/MainView/MainView.swift
Labels: feature, 🤗 리뷰 기다리는중

#81 [Feature] 프로필 설정 뷰 완성 작업
  C3-4T2D/App/Router.swift
  C3-4T2D/Model/SwiftDataManager.swift
  C3-4T2D/Model/User/User.swift
  C3-4T2D/View/ContentView.swift
  C3-4T2D/View/Local/MainHeader.swift
  C3-4T2D/View/MainView/MainView.swift
  C3-4T2D/View/OnboardingView/OnboardingView.swift
  C3-4T2D/View/ProfileSettingView/Local/ProfileImageManager.swift
  C3-4T2D/View/ProfileSettingView/Local/ProfileImageSection.swift
  C3-4T2D/View/ProfileSettingView/Local/UserInfoFormSection.swift
  C3-4T2D/View/ProfileSettingView/ProfileSettingView.swift
  C3-4T2D/View/Shared/UserGoalDateField.swift
  C3-4T2D/View/Shared/UserInfoTextField.swift
Labels: enhancement, Components, feature

#88 feat: SplashView UI 및 애니메이션 구현
  C3-4T2D/Assets.xcassets/logo.imageset/Contents.json
  C3-4T2D/Assets.xcassets/logo.imageset/logo.png
  C3-4T2D/Assets.xcassets/mango.imageset/Contents.json
  C3-4T2D/Assets.xcassets/mango.imageset/mango.png
  C3-4T2D/View/SplashView/SplashView.swift
Labels: 📱 UI, 🤗 리뷰 기다리는중

#93 [Feature] cameraview UI / UX 개선 #84
  C3-4T2D.xcodeproj/project.pbxproj
  C3-4T2D/Assets.xcassets/comment.imageset/Contents.json
  C3-4T2D/Assets.xcassets/comment.imageset/vector.svg
  C3-4T2D/Info.plist
  C3-4T2D/Model/Project/Post.swift
  C3-4T2D/View/Create/CreateView.swift
  C3-4T2D/View/Local/ActiveProjectCard.swift
  C3-4T2D/View/Local/GridImageCard.swift
  C3-4T2D/View/Local/MainHeader.swift
  C3-4T2D/View/Local/PostListCard.swift
  C3-4T2D/View/Local/ProjectSectionCard.swift
  C3-4T2D/View/MainView/MainView.swift
  C3-4T2D/View/ProjectView/Component/ImageView.swift
  C3-4T2D/View/ProjectView/Component/LikeCommentBar.swift
  C3-4T2D/View/ProjectView/Component/TextView.swift
  C3-4T2D/View/ProjectView/PostView.swift
Labels: feature

#86 [Feature] confirmationDialog내 '취소' 버튼 명시화
  C3-4T2D/View/MainView/MainView.swift
Labels: Components

#99 [Feature] splash-view-version2 UI 및 데이터연동
  C3-4T2D/App/Router.swift
  C3-4T2D/Assets.xcassets/splash2.imageset/Contents.json
  C3-4T2D/Assets.xcassets/splash2.imageset/splash2 1.svg
  C3-4T2D/Assets.xcassets/splash2.imageset/splash2 2.svg
  C3-4T2D/Assets.xcassets/splash2.imageset/splash2.svg
  C3-4T2D/Model/SwiftDataManager.swift
  C3-4T2D/Model/User/User.swift
  C3-4T2D/View/ContentView.swift
  C3-4T2D/View/MainView/MainView.swift
  C3-4T2D/View/OnboardingView/OnboardingView.swift
  C3-4T2D/View/ProfileSettingView/Local/ProfileImageManager.swift
  C3-4T2D/View/ProfileSettingView/ProfileSettingView.swift
  C3-4T2D/View/SplashView/SplashView.swift
  C3-4T2D/View/SplashView/SplashView2.swift
Labels: enhancement, feature, 🤗 리뷰 기다리는중

#107 [Hotfix] lightmode 설정 누락 복원
  C3-4T2D.xcodeproj/project.pbxproj
  C3-4T2D/Info.plist
Labels: 🐞 bug

#108 [Feature] 프로젝트 진행단계 저장기능 구현 #80
  C3-4T2D/Model/Project/Post.swift
  C3-4T2D/Model/SwiftDataManager.swift
  C3-4T2D/View/Create/CreateView.swift
  C3-4T2D/View/Create/Local/ProcessStage.swift
  C3-4T2D/View/MainView/MainView.swift
  C3-4T2D/View/ProjectView/PostView.swift
Labels: feature

#113 [Feature] 엘립스 버튼 터치영역 확장 및 컨텍스트메뉴 아이콘 추가 #111
  C3-4T2D/View/ProjectView/PostView.swift
Labels: enhancement, 🤗 리뷰 기다리는중

#120 [Hotfix] merge과정에서 발생한 에러 수정
  C3-4T2D/View/Create/CreateView.swift
  C3-4T2D/View/Create/EditView.swift
Labels: 🐞 bug

#122 [Feature] UI 개선작업 #121
  C3-4T2D/Utils/KeyboardObserver.swift
  C3-4T2D/View/Create/CreateView.swift
  C3-4T2D/View/Create/EditView.swift
  C3-4T2D/View/Local/ActiveProjectCard.swift
  C3-4T2D/View/Local/GridImageCard.swift
  C3-4T2D/View/Local/PostListCard.swift
  C3-4T2D/View/Local/ProjectSectionCard.swift
  C3-4T2D/View/MainView/MainView.swift
Labels: 🤗 리뷰 기다리는중

#129 [Feature] 앨범 기능 구현 #124
  C3-4T2D/View/Create/Local/CreatePhoto.swift
  C3-4T2D/View/Create/Local/CustomPhotoPickerModal.swift
  C3-4T2D/View/PhotoEditView/Crop/CropView.swift
Labels: feature, 🤗 리뷰 기다리는중

#138 [Feature] CategorySelector UX개선
  C3-4T2D/View/Create/CreateView.swift
  C3-4T2D/View/Create/Local/ProjectSelector.swift
Labels: 🐞 bug, enhancement
